### PR TITLE
Bump version to Bump version to 13.5.2

### PR DESCRIPTION
**Pull request by vfishv**
please release a new version

### CODE REVIEW

**Comment by rubyonrails3** [comment]
@vfishv will this fix shizuku on Android QPR2 beta?

**Comment by vfishv** [comment]
> @vfishv will this fix shizuku on Android QPR2 beta?

Yes

**Comment by rubyonrails3** [comment]
> > @vfishv will this fix shizuku on Android QPR2 beta?
> 
> Yes

If you can share the debug apk, I'll be happy to test this on my Pixel 8 Pro.

**Comment by vfishv** [comment]
> > > @vfishv will this fix shizuku on Android QPR2 beta?
> > 
> > 
> > Yes
> 
> If you can share the debug apk, I'll be happy to test this on my Pixel 8 Pro.

https://github.com/RikkaApps/Shizuku/actions/runs/6922136041

**Comment by rubyonrails3** [comment]
> > > > @vfishv will this fix shizuku on Android QPR2 beta?
> > > 
> > > 
> > > Yes
> > 
> > 
> > If you can share the debug apk, I'll be happy to test this on my Pixel 8 Pro.
> 
> https://github.com/RikkaApps/Shizuku/actions/runs/6922136041

Awesome it's working now. Thanks 👍

**Comment by dtaluthge** [comment]
Can confirm this is working on pixel 6 pro as well in qpr 2

**Comment by vfishv** [comment]
> Can confirm this is working on pixel 6 pro as well in qpr 2

why not try it?

**Comment by morpheus092511** [comment]
We're is the apk I clicked link above but nothing downloadable on the page that opens

**Review by Romanrazo — APPROVED** [review]

**Pull request merged**
