### PR TITLE
Add Github Actions CI.

### PR DESCRIPTION
**Pull request by ryuunoakaihitomi**

### CODE REVIEW

**Comment by ryuunoakaihitomi** [comment]
You seem to have no intention of merging this (or even deploying a CI? I don't know).
Close.

**Comment by RikkaW** [comment]
I'm busying doing other projects and unfamiliar with Github Actions, so I want to look at this later.

**Comment by ryuunoakaihitomi** [comment]
That's OK, just keep your pace. It is indeed a little painful to debug this stuff.
You may have your own ideas on how to CI it. If these can help you as the templates, that would be great.

**Comment by RikkaW** [comment]
If you have the "changes not reflecting" problem, enable the "Always install with package manager" option in "Edit configurations" in Android Studio.

**Pull request closed without merging**
