### PR TITLE
Updated -hu strings

### LINKED ISSUE #287: Json Genie: 20230403_223501
Shared with JSON Genie (Android): http://play.google.com/store/apps/details?id=com.tuyware.jsongenie

### PR DESCRIPTION
**Pull request by gidano**

### CODE REVIEW

**Review by Gdakgdak22 — CHANGES_REQUESTED** [review]
Gracias

**Comment by chirifouhamed-tech** [comment]
Help

**Comment by chirifouhamed-tech** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by chirifouhamed-tech** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Pull request merged**
